### ISSUE TITLE
Does not support reddituploads.

### ISSUE THREAD

**Issue by tankoks** [makuto/redditLikedSavedImageDownloader#4]
Scraper does not support reddituploads or imgur albums

**Comment by makuto** [comment]
Hey tankoks, 
Thanks for using my script!

I just added reddituploads support as of b3e1309462457718ec7c9432184f2a0520d003ec. Imgur album support is something I haven't approached yet, but I took a look at the API today and have an idea of how it will be done.

I'll close this issue once I complete Imgur Albums.

**Comment by makuto** [comment]
As of 6b98c411db7c747d63dc160ca0a334e86430f2af, Imgur Albums are now supported! Make sure to install the Imgur API before/after getting the latest version of the script:
`pip install imgurpython`
