### ISSUE TITLE
Don't download liked posts

### ISSUE THREAD

**Issue by sn0wyfall** [makuto/redditLikedSavedImageDownloader#8]
Hey!

So I noticed that the script seems to cache liked posts. Is there a way to prevent this from happening? It would be great if there were an option for this. 

This was actually mentioned and answered in issue #1, where you said:

    First, to make it so that it only does saved images, open imageSaver.py in
    a text editor and add a '#' in front of lines 53, 57, 60, and 63.

This doesn't seem to be correct (anymore) as far as I can see, because for example line 57 is a blank line. I'd appreciate it if you could post updated instructions!

**Comment by makuto** [comment]
47197ce4ee43036ec55ad2d0e7a86676fc3ec024 adds two options `Reddit_Save_Liked` and
`Reddit_Save_Saved`. You can add `Reddit_Save_Saved=False` to your `settings.txt` to only get Liked stuff.

**Comment by sn0wyfall** [comment]
Woooooowwww! This is amazing! I can't believe you did that so quickly. Maybe you had written it already, or maybe you didn't. Either way, that's really impressive. Of course I'm saying that because I'm happy you actually did that, but in any case I'm quite impressed, too. Thanks so much!
