### ISSUE TITLE
Just wanted to say thank you

### ISSUE THREAD

**Issue by sn0wyfall** [makuto/redditLikedSavedImageDownloader#9]
Hey, I just wanted to say thanks. I mentioned this elsewhere, but I was looking for something like this, and I just couldn't find anything. This script surpasses my expectations, by far, by categorizing the images into individual subreddits and sequentially downloading them (so I can sort them by date, for example). Believe it or not, before this I was *manually* downloading the images, and of course since Imgur randomizes the image names I was saving them with nonsensical names (I really didn't want to manually rename them to match the post title as well!).

And also the fact that you replied to my issues, so quickly as well, and helped me fix them. That is amazing.

So that being said, you saved me from a lot of trouble, so *thank you so very much*. If I wasn't a poor student, I would donate to you. For now, however, you'll have to do with my adulation. Thank you again!

**Comment by makuto** [comment]
Thank you very much for your appreciation! People like you are the reason why I keep working on this script. Let me know if you have any other requests and I'll see what I can do. Have fun letting this script fill up your hard drive :)!
